/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital_management_system;

import java.sql.*;
import DatabaseConnection.DBConnection;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Mahapatra
 */
public class AddDiagnosisDetails extends javax.swing.JFrame {

    /**
     * Creates new form AddDiagnosisDetails
     */
    public AddDiagnosisDetails() {
        initComponents();
        wardTypeLabel.setVisible(false);
        wardComboBox.setVisible(false);
        invalidMessageLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        invalidMessageLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        symptomsTextField = new javax.swing.JTextField();
        diagnosisTextField = new javax.swing.JTextField();
        medicinesTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        wardReqCheckBox = new javax.swing.JCheckBox();
        wardTypeLabel = new javax.swing.JLabel();
        wardComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 350));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(754, 471));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("PatientID:");
        jLabel1.setPreferredSize(new java.awt.Dimension(64, 26));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 58, 64, 20));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 57, 64, 26));

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/search_icon.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.setPreferredSize(new java.awt.Dimension(64, 26));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 130, 40));

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PatientID", "Name", "Age", "Contact No."
            }
        ));
        jScrollPane1.setViewportView(searchResultTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 101, 680, 98));

        invalidMessageLabel.setFont(new java.awt.Font("Segoe UI Semilight", 2, 14)); // NOI18N
        invalidMessageLabel.setForeground(new java.awt.Color(255, 0, 51));
        invalidMessageLabel.setText("Invalid PatientID!");
        getContentPane().add(invalidMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Symptoms:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 227, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Diagnosis:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 271, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Medicines Prescribed:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 315, -1, -1));

        symptomsTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(symptomsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 224, 200, -1));

        diagnosisTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(diagnosisTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 268, 200, -1));

        medicinesTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(medicinesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 312, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Ward Required?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 356, -1, -1));

        wardReqCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardReqCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(wardReqCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 356, -1, -1));

        wardTypeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        wardTypeLabel.setText("Ward Type:");
        getContentPane().add(wardTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 397, -1, -1));

        wardComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wardComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Dual Sharing", "Single" }));
        getContentPane().add(wardComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 394, -1, -1));

        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/save_icon.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/close_icon.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/background_image.jpg"))); // NOI18N
        backgroundImage.setPreferredSize(new java.awt.Dimension(754, 471));
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void wardReqCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardReqCheckBoxActionPerformed
        if(wardReqCheckBox.isSelected()){
            wardTypeLabel.setVisible(true);
            wardComboBox.setVisible(true);
        }
        else{
            wardTypeLabel.setVisible(false);
            wardComboBox.setVisible(false);
        }
    }//GEN-LAST:event_wardReqCheckBoxActionPerformed
    public int flag = 0;
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String enteredPatientID = searchTextField.getText();
        try{
            Connection con = DBConnection.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("SELECT * FROM PATIENT WHERE patientID = '" + enteredPatientID + "'");
            searchResultTable.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first()){
                invalidMessageLabel.setVisible(true);
            }
            else{
                searchTextField.setEditable(false);
                flag = 1;
                invalidMessageLabel.setVisible(false);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Commands!");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(flag == 1){
            String patientID = searchTextField.getText();
            String symptoms = symptomsTextField.getText();
            String diagnosis = diagnosisTextField.getText();
            String medicines = medicinesTextField.getText();
            String wardReq = wardReqCheckBox.isSelected() ? "Yes" : "No";
            String ward = "";
            if(wardReqCheckBox.isSelected()){
                ward = (String) wardComboBox.getSelectedItem();
            }
            else{
                ward = null;
            }
            
            try{
                Connection con = DBConnection.getCon();
                Statement st = con.createStatement();
                st.executeUpdate(String.format("INSERT INTO patientDiagnosisReports VALUES ('%s','%s','%s','%s','%s','%s')",
                        patientID, symptoms, diagnosis, medicines, wardReq, ward));
                
                JOptionPane.showMessageDialog(null, "Successfully added.");
                setVisible(false);
                new AddDiagnosisDetails().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Please enter valid details.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please enter a PatientID.");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDiagnosisDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField diagnosisTextField;
    private javax.swing.JLabel invalidMessageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medicinesTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextField symptomsTextField;
    private javax.swing.JComboBox<String> wardComboBox;
    private javax.swing.JCheckBox wardReqCheckBox;
    private javax.swing.JLabel wardTypeLabel;
    // End of variables declaration//GEN-END:variables
}
