/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital_management_system;

import javax.swing.JOptionPane;
import java.sql.*;
import DatabaseConnection.DBConnection;
import java.time.LocalDate;
/**
 *
 * @author Mahapatra
 */
public class AddPatient extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
    public AddPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        patientIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        contactNoLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        bloodGroupLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        majorDiseasesLabel = new javax.swing.JLabel();
        patientIDText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        contactNoText = new javax.swing.JTextField();
        ageText = new javax.swing.JTextField();
        bloodGroupText = new javax.swing.JTextField();
        majorDiseasesText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        addressText = new javax.swing.JTextField();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 350));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(520, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/close_icon.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 40, -1));

        patientIDLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        patientIDLabel.setText("Patient ID:");
        getContentPane().add(patientIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 72, -1, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nameLabel.setText("Name:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 112, -1, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 234, -1, -1));

        contactNoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        contactNoLabel.setText("Contact No.:");
        getContentPane().add(contactNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 152, -1, -1));

        ageLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ageLabel.setText("Age:");
        getContentPane().add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 192, -1, -1));

        genderLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        genderLabel.setText("Gender:");
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 234, -1, -1));

        bloodGroupLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bloodGroupLabel.setText("Blood Group:");
        getContentPane().add(bloodGroupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 275, -1, -1));

        addressLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addressLabel.setText("Address:");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 315, -1, -1));

        majorDiseasesLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        majorDiseasesLabel.setText("Major Diseases:");
        getContentPane().add(majorDiseasesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        getContentPane().add(patientIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 72, 230, -1));
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 112, 230, -1));
        getContentPane().add(contactNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 152, 230, -1));
        getContentPane().add(ageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 192, 230, -1));
        getContentPane().add(bloodGroupText, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 275, 35, -1));
        getContentPane().add(majorDiseasesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 230, -1));

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/save_icon.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 110, 40));
        getContentPane().add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 315, 230, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/background_image.jpg"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String patientID = patientIDText.getText();
        String name = nameText.getText();
        String contactNumber = contactNoText.getText();
        String age = ageText.getText();
        String gender = (String) genderComboBox.getSelectedItem();
        String bloodGroup = bloodGroupText.getText();
        String address = addressText.getText();
        String majorDiseases = majorDiseasesText.getText();
        String date = LocalDate.now().toString();
        
        try{
            Connection con = DBConnection.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO PATIENT VALUES('" 
                    + patientID +"','" + name + "','" + contactNumber + "','" + age + "','" + gender + "','" + bloodGroup + "','" 
                    + address + "','" + majorDiseases + "','" + date + "')");
            
            JOptionPane.showMessageDialog(null, "Patient added Successfully!");
            setVisible(false);
            new AddPatient().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Details. Please check your entered data.");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageText;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel bloodGroupLabel;
    private javax.swing.JTextField bloodGroupText;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel contactNoLabel;
    private javax.swing.JTextField contactNoText;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel majorDiseasesLabel;
    private javax.swing.JTextField majorDiseasesText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel patientIDLabel;
    private javax.swing.JTextField patientIDText;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
