/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Mahapatra
 */
public class HomePage extends javax.swing.JFrame {
    /**
     * Creates new form Homepage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPatientButton = new javax.swing.JButton();
        addDiagnosisButton = new javax.swing.JButton();
        patientHistoryButton = new javax.swing.JButton();
        manageRecordsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        hospitalInfoButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addPatientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/add_patient_icon.png"))); // NOI18N
        addPatientButton.setText("Add Patient");
        addPatientButton.setPreferredSize(new java.awt.Dimension(235, 60));
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addPatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 100, -1, -1));

        addDiagnosisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/diagnosis_info_icon.png"))); // NOI18N
        addDiagnosisButton.setText("Add Diagnosis Details");
        addDiagnosisButton.setPreferredSize(new java.awt.Dimension(235, 60));
        addDiagnosisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiagnosisButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addDiagnosisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        patientHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/medical_history_icon.png"))); // NOI18N
        patientHistoryButton.setText("Patient Medical Records");
        patientHistoryButton.setPreferredSize(new java.awt.Dimension(235, 60));
        patientHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHistoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(patientHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 100, -1, -1));

        manageRecordsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/manage_patient_records_icon.png"))); // NOI18N
        manageRecordsButton.setText("Update Patient Records");
        manageRecordsButton.setPreferredSize(new java.awt.Dimension(235, 60));
        manageRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 100, -1, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/logout_icon.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, -1, -1));

        hospitalInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/hospital_info_icon.png"))); // NOI18N
        hospitalInfoButton.setText("Hospital Information");
        hospitalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hospitalInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/background_image.jpg"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        new AddPatient().setVisible(true);
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int selected = JOptionPane.showConfirmDialog(null, "Are you sure?", "Logout", JOptionPane.YES_NO_OPTION);
        if(selected == 0){
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addDiagnosisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiagnosisButtonActionPerformed
        new AddDiagnosisDetails().setVisible(true);
    }//GEN-LAST:event_addDiagnosisButtonActionPerformed

    private void patientHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHistoryButtonActionPerformed
        new PatientMedicalRecords().setVisible(true);
    }//GEN-LAST:event_patientHistoryButtonActionPerformed

    private void manageRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRecordsButtonActionPerformed
        new UpdatePatientRecords().setVisible(true);
    }//GEN-LAST:event_manageRecordsButtonActionPerformed

    private void hospitalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalInfoButtonActionPerformed
        new HospitalInformation().setVisible(true);
    }//GEN-LAST:event_hospitalInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomePage hp = new HomePage();
                hp.setVisible(true);
                hp.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDiagnosisButton;
    private javax.swing.JButton addPatientButton;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton hospitalInfoButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageRecordsButton;
    private javax.swing.JButton patientHistoryButton;
    // End of variables declaration//GEN-END:variables
}
