/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital_management_system;

import DatabaseConnection.DBConnection;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author Mahapatra
 */
public class UpdatePatientRecords extends javax.swing.JFrame {

    /**
     * Creates new form ManagePatientRecords
     */
    public UpdatePatientRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        bloodGroupLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        majorDiseasesLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        bloodGroupTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        diseasesTextField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();
        genderComboBox = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 350));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(520, 500));
        setSize(new java.awt.Dimension(520, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientIDLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        patientIDLabel.setText("PatientID:");
        getContentPane().add(patientIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 69, -1, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nameLabel.setText("Name:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 137, -1, -1));

        contactLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        contactLabel.setText("Contact No.:");
        getContentPane().add(contactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 181, -1, -1));

        ageLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ageLabel.setText("Age:");
        getContentPane().add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 225, -1, -1));

        genderLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        genderLabel.setText("Gender:");
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 266, -1, -1));

        bloodGroupLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bloodGroupLabel.setText("Blood Group:");
        getContentPane().add(bloodGroupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 309, -1, -1));

        addressLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addressLabel.setText("Address:");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 353, -1, -1));

        majorDiseasesLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        majorDiseasesLabel.setText("Major Diseases:");
        getContentPane().add(majorDiseasesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 397, -1, -1));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 66, 60, -1));

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 134, -1, -1));

        contactTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(contactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 178, -1, -1));

        ageTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 222, 100, -1));

        bloodGroupTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bloodGroupTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(bloodGroupTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 306, -1, -1));

        addressTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 350, -1, -1));

        diseasesTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diseasesTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(diseasesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 394, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/close_icon.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 266, 100, -1));

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/save_icon.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 446, -1, -1));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/search_icon.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 65, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/background_image.jpg"))); // NOI18N
        backgroundImage.setText("jLabel10");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String enteredID = searchTextField.getText();
        try{
            Connection con = DBConnection.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("SELECT * FROM PATIENT WHERE patientID = '" + enteredID + "'");
            if(rs.next()){
                nameTextField.setText(rs.getString(2));
                contactTextField.setText(rs.getString(3));
                ageTextField.setText(rs.getString(4));
                String s = rs.getString(5);
                if(s.equals("Male")){
                    genderComboBox.setSelectedIndex(0);
                }
                else if(s.equals("Female")){
                    genderComboBox.setSelectedIndex(1);
                }
                else{
                    genderComboBox.setSelectedIndex(2);
                }
                bloodGroupTextField.setText(rs.getString(6));
                addressTextField.setText(rs.getString(7));
                diseasesTextField.setText(rs.getString(8));
            }
            else{
                JOptionPane.showMessageDialog(null, "PatientID doesn't exist!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Commands!");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String patientID = searchTextField.getText();
        String name = nameTextField.getText();
        String contactNumber = contactTextField.getText();
        String age = ageTextField.getText();
        String gender = (String) genderComboBox.getSelectedItem();
        String bloodGroup = bloodGroupTextField.getText();
        String address = addressTextField.getText();
        String majorDiseases = diseasesTextField.getText();
        
        try{
            Connection con = DBConnection.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("UPDATE PATIENT SET NAME = '" + name + "', contactNumber = '" + contactNumber + "', age = '" + age + "', gender = '" + gender 
                    + "', bloodGroup = '" + bloodGroup + "', address = '" + address + "', majorDiseases = '" + majorDiseases + "' WHERE patientID = '" + patientID + "'");
            
            JOptionPane.showMessageDialog(null, "Patient details updated successfully!");
            setVisible(false);
            new UpdatePatientRecords().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Details. Please check your entered data.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePatientRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel bloodGroupLabel;
    private javax.swing.JTextField bloodGroupTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField diseasesTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel majorDiseasesLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel patientIDLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
